swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: petstore.swagger.io
basePath: /v2
schemes:
  - https
paths:
  /pet/7574746:
    get:
      summary: Returns a list of pet.
      produces:
        - application/json
      responses:
        200:
          description: OK